### ISSUE TITLE
{"message":"Failed to resolve package name"}

### ISSUE THREAD

**Issue by diogomsantos** [joshmarshall/bintray-upload#1]
bintray-upload kodi-bin_16.0-2~jessie_armhf.deb

Does this look correct?
- Name: kodi-bin
- Version: 16.0-2~jessie
- Architecture: armhf
- Distribution: jessie
- Component: main
- BinTray Repo: pipplware/raspbian

(Please enter y/n): y
Submitting package...
Traceback (most recent call last):
  File "/usr/local/bin/bintray-upload", line 9, in <module>
    load_entry_point('bintray-upload==0.1.2', 'console_scripts', 'bintray-upload')()
  File "/usr/local/lib/python2.7/dist-packages/bintray_upload.py", line 99, in main
    response.status_code, response.text))
Exception: Failed to submit package: 400
{"message":"Failed to resolve package name"}

Is this still working ? I keep getting this error, googling shows nothing related...

**Comment by joshmarshall** [comment]
Hi @diogomsantos -- I haven't seen this issue, but my first thought is around the ~ in the version potentially not being url-encoded / decoded properly. I will try to look into it later, but if you can try something immediately you might try urlencode'ing the version as a start?

**Comment by joshmarshall** [comment]
@diogomsantos Also just to verify -- you've created the package in that repo first, correct? I don't see it at https://bintray.com/pipplware/raspbian , but it could be private.

**Comment by diogomsantos** [comment]
Yeah, I am new to bintray and it was because I hadn't created a package. My objective was to use bintray as a mirror of my Debian Repository, which has a lot of packages, and that would take a lot of time. I ended up using it in another way. You can close this, thanks for the help.

**Comment by joshmarshall** [comment]
@diogomsantos Thanks, let me know if you see any other problems!
